log:
  name: "Health_photo_voltaic_systems"
  experiment_name: 'solar_basicCnn_v00'
  log_dir: '/home/baha/codes/solar_data/InfraredSolarModules'
  frequency:
    iteration: 1
  root:

checkpoint:
  init: null
  frequency:
    epoch: 1

#############

data:
  train_dir: '/home/baha/codes/solar_data/InfraredSolarModules/train'
  val_dir: '/home/baha/codes/solar_data/InfraredSolarModules/val'
  cifar100_train_dir: '/home/baha/codes/solar_data/cifar100_data/train'
  cifar100_val_dir: '/home/baha/codes/solar_data/cifar100_data/val'
  batch_size: 32
  num_workers: 2

  preprocessing:
    mean: 0.6512266
    std: 0.15099779

train:
  epoch: 200
  loss:
  weight: null
  number_class: 12

  optim:
    method: SGD
    lr: 0.1
    weight_decay: 0.0001
    momentum: 0.9

  model:
    model_name: DenseNet  # cnn
    prtrained: '/home/baha/codes/solar_data/cifar100_data/model_dense121_cifar100.pth' # 'cifar100'


scheduler:
  method: MultiStepLR
  step_size: [50, 100, 150]
  gamma: 0.1
