log:
  name: "Health_photo_voltaic_systems"
  experiment_name: 'solar_basicCnn_v00'
  log_dir: '/content/gdrive/MyDrive/Colab_Notebooks/logs/solar/basic_conv'
  frequency:
    iteration: 1
  root:

checkpoint:
  init: '/content/gdrive/MyDrive/Colab_Notebooks/logs/solar/basic_conv/model_epoch64.pth'
  frequency:
    epoch: 1

#############

data:
  train_dir: '/content/gdrive/MyDrive/Colab_Notebooks/jua_solar/solar_data/InfraredSolarModules/train'
  val_dir: '/content/gdrive/MyDrive/Colab_Notebooks/jua_solar/solar_data/InfraredSolarModules/val'
  cifar100_train_dir: '/content/gdrive/MyDrive/Colab_Notebooks/cifar100_data/train'
  cifar100_val_dir: '/content/gdrive/MyDrive/Colab_Notebooks/cifar100_data/val'
  batch_size: 128
  num_workers: 16



  preprocessing:
    mean: 0.6512266
    std: 0.15099779

train:
  epoch: 150  #200
  loss:
  weight: null
  number_class: 100  #for cifar100,  #for solar data 12

  optim:
    method: SGD
    lr: 0.1
    weight_decay: 0.0001
    momentum: 0.9

  model:
    model_name: densenet  # cnn, resnet20, resnet32
    prtrained: 'cifar100' #cifar10, null


scheduler:
  method: MultiStepLR
  step_size: [2, 60, 120]  #solarData [50, 100, 150]
  gamma: 0.1
